### PR TITLE
Add default entryParser, respect custom entryParser

### PR DESCRIPTION
**Pull request by ofaltins**

### CODE REVIEW

**Comment by jsumners** [comment]
Thank you for the submission. Are you able to add a unit test for this functionality?

**Comment by ofaltins** [comment]
Sure thing!

**Comment by jsumners** [comment]
Looking great. One other thing: does the documentation need to be updated?

**Comment by ofaltins** [comment]
Nope. The functionality matches what is already documented. Referencing #21

**Comment by jsumners** [comment]
Excellent. Thank you for the contribution.

**Pull request merged**
