### PR TITLE
fix for infinite loop in getUsersForGroup.js

### PR DESCRIPTION
**Pull request by jurjendijkstra**
Fix for issue 58 "getUsersForGroup crashes if group is member of itself"

### CODE REVIEW

**Comment by jurjendijkstra** [comment]
Yes, I am looking into the test, see how I can add some

**Comment by jurjendijkstra** [comment]
This is not easy....  both existing test cases for getUsersForGroup are testing a group that has no subgroups. When I add a new test case for a group with subgroups then I see that it isn't diving into the subgroups at all. I suppose there's something wrong with search.js in test/mockServer so it returns only users and no groups. 

What I wanted to do is simply add a member (a new user) to group "grpb", then call getUsersForGroup for "grpa" and prove that it recurses infinitely. Right now it just returns the user in  group grpa without even trying to dive into grpb.

I doubt if I can improve the mockServer but will keep trying some more

**Comment by jurjendijkstra** [comment]
At last! I have improved the unittest, yeah.  
The mockserver can now recurse into subgroups for getUsersForGroup, so the unittest can prove that circular groups grpa - grpb are not running forever.

**Comment by jsumners** [comment]
Awesome! Thank you for digging into this and improving it. I'll merge and release soon.

**Comment by jurjendijkstra** [comment]
Good to see you're still up. Our customer is already using the patch in production :-) so it's good if it is in a proper release. I will delete my fork immediately after that.
Have a good weekend

**Comment by jsumners** [comment]
I'm in the US Eastern timezone (currently UTC-4). But I can't work on OSS stuff during business hours. I'll deal with this either tonight or some time over the weekend.

**Comment by jurjendijkstra** [comment]
there is no hurry

**Comment by jsumners** [comment]
Published under `activedirectory2@next`.

I'm not issuing any new v1 releases. If you must, you can install it from GitHub via the commit SHA.

**Comment by jurjendijkstra** [comment]
Thanks for accepting the PR. About releases: ok by me that you are not issuing new v1 releases but what is activedirectory2@next, it does not appear on the releases list at all? More to the point should I expect breaking changes when I upgrade from 1.3 to next?

**Comment by jsumners** [comment]
https://docs.npmjs.com/cli/dist-tag#purpose

> More to the point should I expect breaking changes when I upgrade from 1.3 to next?

Ideally, no. You can review the commits made to the `next` branch to see what is included.

**Pull request merged**
