### PR TITLE
revert escaping, remove "snazzy" dep

### PR DESCRIPTION
**Pull request by jurjendijkstra**
1. fix for issue #49:  non-US-ASCII characters (like Cyrillic) were escaped in a wrong way, resulting in a query that did not return groupmembers.  Tests show that the attempt to escape seems unnecessary, so this PR removes it.
2. moved "snazzy" dependency to devDependency as requested in issue #50

### CODE REVIEW

**Comment by jsumners** [comment]
I'm confused. What is this one?

**Comment by jurjendijkstra** [comment]
yeah I am confused too. I did not know how to add a new commit to an existing PR so I thought I had to make a new PR.  I think it is garbage now.

**Comment by jurjendijkstra** [comment]
I will just delete my fork, see if that removes this PR

**Comment by jurjendijkstra** [comment]
fork jurjendijkstra/node-activedirectory is now deleted

**Comment by jsumners** [comment]
You simply add a new commit to your local branch and push it up to your GitHub copy. The new commit will automatically be added to the existing PR.

**Comment by jurjendijkstra** [comment]
Wow that's easy and makes sense too. Good to know for the next time. Thanks for the quick merge and for publishing the new version!

**Pull request closed without merging**
